[package]
name = "blind_decode"
version = "0.1.0"
authors = ["JP"]

[dependencies]
nalgebra = "*"
rand = "*"
regex = "*"
log = "*"
env_logger = "*"

[profile.release]
debug = true

[lib]
name = "blindsolver"
path = "src/solver.rs"

[[bin]]
name = "main"
path = "src/main.rs"
