[package]
name = "blind_decode"
version = "0.2.0"
authors = ["JP", "Tom"]

[dependencies]
nalgebra = "*"
rand = "*"
regex = "*"
log = "*"
env_logger = "*"

[profile.release]
debug = true

[lib]
name = "blindsolver"
path = "src/solver.rs"
