[package]
name = "blind_decode"
version = "0.4.0"
authors = ["JP", "Tom"]

[dependencies]
nalgebra = "*"
rand = "*"
regex = "*"
log = "*"
env_logger = "*"
fnv = "1.0.3"
num_cpus = "*"

[profile.release]
debug = true

[lib]
name = "blindsolver"
path = "src/solver.rs"

